# Generated by Django 6.0.5 on 2026-05-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0006_move_assignment_comments_to_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerability',
            name='assignment_comment',
        ),
    ]
