# Generated by Django 6.0.5 on 2026-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0007_remove_assignment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('TEAMLEADER', 'Teamleader'), ('DEVELOPER', 'Developer'), ('ANALYST', 'Analyst')], default='ANALYST', max_length=10),
        ),
    ]
