name: RemediTrack CI/CD

on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          
      - name: Run Django Tests
        run: |
          cd src
          echo "SECRET_KEY=testing" > .env
          python manage.py test vulnerabilities

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Secret Existence
        run: |
          if [ -z "$SSH_KEY" ]; then echo "❌ SSH_PRIVATE_KEY is MISSING"; else echo "✅ SSH_PRIVATE_KEY is present"; fi
          if [ -z "$B_IP" ]; then echo "❌ BASTION_IP is MISSING"; else echo "✅ BASTION_IP is present"; fi
          if [ -z "$S_IP" ]; then echo "❌ SERVER_IP is MISSING"; else echo "✅ SERVER_IP is present"; fi
          if [ -z "$E_FILE" ]; then echo "❌ ENV_FILE is MISSING"; else echo "✅ ENV_FILE is present"; fi
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          B_IP: ${{ secrets.BASTION_IP }}
          S_IP: ${{ secrets.SERVER_IP }}
          E_FILE: ${{ secrets.ENV_FILE }}
      
      - name: Manual SSH Key Setup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Deploy to AWS via Bastion
        run: |
          echo "Host bastion" > ~/.ssh/config
          echo "  HostName ${{ secrets.BASTION_IP }}" >> ~/.ssh/config
          echo "  User ubuntu" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "" >> ~/.ssh/config
          echo "Host app-server" >> ~/.ssh/config
          echo "  HostName ${{ secrets.SERVER_IP }}" >> ~/.ssh/config
          echo "  User ubuntu" >> ~/.ssh/config
          echo "  ProxyJump bastion" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

          rsync -avz --exclude '.git' ./ app-server:/home/ubuntu/Remeditrack-Devops/

          echo "${{ secrets.ENV_FILE }}" > .env.tmp
          scp .env.tmp app-server:/home/ubuntu/Remeditrack-Devops/src/.env
          rm .env.tmp

          ssh app-server "cd ~/Remeditrack-Devops/src && docker compose up -d --build && docker compose exec -T web python manage.py migrate --noinput && docker compose exec -T web python manage.py collectstatic --noinput"
